allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  aws-crt: true
  bcrypt: true
  canvas: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
