import { getHomepageImage } from "@/lib/homepage/storage";
import { loadPublished, notFound, OK_HEADERS } from "@/lib/homepage/serve";

// Public AI-generated image of a prospect preview. The object may be PNG/JPEG/WebP
// depending on the provider, so we serve its stored (detected) content-type. The
// name is a stored filename, not user input (generated by the job).
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ slug: string; name: string }> }
): Promise<Response> {
  const { slug, name } = await params;
  // Defense-in-depth: only serve simple filenames within the slug's images dir.
  if (!/^[a-z0-9._-]+$/i.test(name)) return notFound();
  const img = await loadPublished(slug, (s) => getHomepageImage(s, name));
  if (img === null) return notFound();
  return new Response(new Uint8Array(img.buffer), {
    status: 200,
    headers: { "content-type": img.contentType, ...OK_HEADERS },
  });
}
