import { create } from "xmlbuilder2";

export function fillXmlTemplate(data: any, myCompany: any) {
  const xml = create({ version: "1.0", encoding: "UTF-8" })
    .ele("MoneyData", {
      CompanyVAT: myCompany.VAT_number,
      CompanyCode: data.CompanyCode,
      FiscalYearFrom: data.FiscalYearFrom,
      FiscalYearTo: data.FiscalYearTo,
      description: data.description,
      ShortDescription: data.ShortDescription,
      ExpDate: data.ExpDate,
      ExpTime: data.ExpTime,
      RecordSelection: data.RecordSelection,
      GUID: data.GUID,
    })
    .ele("Document")
    .txt(data.variable_symbol)
    .up() // move back to the parent element
    .ele("GUID")
    .up()
    .ele("Issued")
    .txt(
      data.date_of_case ? data.date_of_case.toISOString().split("T")[0] : null
    )
    .up()
    .ele("AccountingDate")
    .txt(data.date_tax ? data.date_tax.toISOString().split("T")[0] : null)
    .up()
    .ele("TaxDate")
    .txt(data.date_tax ? data.date_tax.toISOString().split("T")[0] : null)
    .up()
    .ele("Due")
    .txt(data.date_due ? data.date_due.toISOString().split("T")[0] : null)
    .up()
    .ele("Received")
    .txt(
      data.date_received ? data.date_received.toISOString().split("T")[0] : null
    )
    .up()
    .ele("TaxableDate")
    .up()
    .ele("ConstantSymbol")
    .txt(data.constant_symbol)
    .up()
    .ele("VariableSymbol")
    .txt(data.variable_symbol)
    .up()
    .ele("ReceivedDocument")
    .txt(data.variable_symbol)
    .up()
    .ele("Settled")
    .up()
    .ele("Supplier")
    .ele("TradeName")
    .txt(data.partner)
    .up()
    .ele("TradeAddress")
    .ele("Street")
    .txt(data.partner_business_street)
    .up()
    .ele("City")
    .txt(data.partner_business_city)
    .up()
    .ele("PostalCode")
    .txt(data.partner_business_zip)
    .up()
    .ele("Country")
    .txt(data.partner_business_country)
    .up()
    .ele("CountryCode")
    .txt(data.partner_business_country_code)
    .up()
    .ele("CompanyID")
    .txt(data.partner_VAT_number)
    .up()
    .ele("TaxID")
    .txt(data.partner_TAX_number)
    .up()
    .ele("BillingAddress")
    .ele("Street")
    .txt(data.partner_street)
    .up()
    .ele("City")
    .txt(data.partner_city)
    .up()
    .ele("PostalCode")
    .txt(data.partner_zip)
    .up()
    .ele("Country")
    .txt(data.partner_country)
    .up()
    .ele("CountryCode")
    .txt(data.partner_country_code)
    .up()
    .up()
    .ele("GUID")
    .up()
    .ele("Phone")
    .ele("Prefix")
    .txt(data.partner_phone_prefix)
    .up()
    .ele("Number")
    .txt(data.partner_phone_number)
    .up()
    .up()
    .ele("Fax")
    .ele("Prefix")
    .txt(data.partner_fax_prefix)
    .up()
    .ele("Number")
    .txt(data.partner_fax_number)
    .up()
    .up()
    .ele("Email")
    .txt(data.partner_email)
    .up()
    .ele("Website")
    .txt(data.partner_website)
    .up()
    .ele("TaxPayer")
    .txt(data.partner_TAX_number ? "1" : "0")
    .up()
    .ele("Individual")
    .txt(data.partner_is_person ? "1" : "0")
    .up()
    .ele("Bank")
    .txt(data.partner_bank)
    .up()
    .ele("Account")
    .txt(data.partner_IBAN)
    .up()
    .up()
    .ele("DomesticShipping")
    .up()
    .ele("InternationalShipping")
    .up()
    .ele("ITSDate")
    .up()
    .ele("Discount")
    .up()
    .ele("ItemList")
    .up()
    .ele("MyCompany")
    .ele("Name")
    .txt(myCompany.company_name)
    .up()
    .ele("Address")
    .ele("Street")
    .txt(myCompany.street)
    .up()
    .ele("City")
    .txt(myCompany.city)
    .up()
    .ele("PostalCode")
    .txt(myCompany.zip)
    .up()
    .ele("Country")
    .txt(myCompany.country)
    .up()
    .ele("CountryCode")
    .txt(myCompany.country_code)
    .up()
    .up()
    .ele("TradeName")
    .txt(myCompany.company_name)
    .up()
    .ele("TradeAddress")
    .ele("Street")
    .txt(myCompany.billing_street)
    .up()
    .ele("City")
    .txt(myCompany.billing_city)
    .up()
    .ele("PostalCode")
    .txt(myCompany.billing_zip)
    .up()
    .ele("Country")
    .txt(myCompany.billing_country)
    .up()
    .ele("CountryCode")
    .txt(myCompany.billing_country_code)
    .up()
    .ele("BillingAddress")
    .ele("Street")
    .txt(myCompany.billing_street)
    .up()
    .ele("City")
    .txt(myCompany.billing_city)
    .up()
    .ele("PostalCode")
    .txt(myCompany.billing_zip)
    .up()
    .ele("Country")
    .txt(myCompany.billing_country)
    .up()
    .ele("CountryCode")
    .txt(myCompany.billing_country_code)
    .up()
    .up()
    .ele("Phone")
    .ele("Prefix")
    .txt(myCompany.phone_prefix)
    .up()
    .ele("Number")
    .txt(myCompany.phone_number)
    .up()
    .up()
    .ele("Fax")
    .ele("Prefix")
    .txt(myCompany.fax_prefix)
    .up()
    .ele("Number")
    .txt(myCompany.fax_number)
    .up()
    .up()
    .ele("Mobile")
    .ele("Prefix")
    .txt(myCompany.mobile_prefix)
    .up()
    .ele("Number")
    .txt(myCompany.mobile_number)
    .up()
    .up()
    .ele("Email")
    .txt(myCompany.email)
    .up()
    .ele("Website")
    .txt(myCompany.website)
    .up()
    .ele("CompanyID")
    .txt(myCompany.VAT_number)
    .up()
    .ele("TaxID")
    .txt(myCompany.TAX_number)
    .up()
    .ele("Bank")
    .txt(myCompany.bank_name)
    .up()
    .ele("Account")
    .txt(myCompany.bank_account)
    .up()
    .ele("BankCode")
    .txt(myCompany.bank_code)
    .up()
    .ele("Individual")
    .txt(myCompany.is_person ? "1" : "0")
    .up()
    .ele("CurrencySymbol")
    .txt(myCompany.currency_symbol)
    .up()
    .ele("CurrencyCode")
    .txt(myCompany.currency)
    .up()
    .up()
    .up()
  return xml.end({ prettyPrint: true });
}
