// AUTO-GENERATED by scripts/plugins/generate-registry.mjs — do not edit.
import type { GeneratedPluginEntry } from "@/lib/plugins/registry";
import public_registry_ares from "@/plugins/registry-ares/plugin";
import public_registry_ares_en from "@/plugins/registry-ares/messages/en.json";
import public_registry_ares_cz from "@/plugins/registry-ares/messages/cz.json";
import public_registry_ares_de from "@/plugins/registry-ares/messages/de.json";
import public_registry_ares_uk from "@/plugins/registry-ares/messages/uk.json";

export const generatedPlugins: GeneratedPluginEntry[] = [
  { source: "public", definition: public_registry_ares, messages: { en: public_registry_ares_en, cz: public_registry_ares_cz, de: public_registry_ares_de, uk: public_registry_ares_uk } },
];
