// AUTO-GENERATED by scripts/plugins/generate-registry.mjs — do not edit.
import type { GeneratedPluginEntry } from "@/lib/plugins/registry";

export const generatedPlugins: GeneratedPluginEntry[] = [
];
