"use server";

import { PrismaClient } from "@/lib/generated/prisma";
import bcrypt from "bcryptjs";
import { signIn, signOut } from "@/auth";
import { AuthError } from "next-auth";
import { sendVerificationEmail } from "@/lib/send-verification-email";

const prisma = new PrismaClient();

export async function registerUser(formData: FormData) {
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;
  const name = formData.get("name") as string;

  if (!email || !password) {
    return { error: "Email and password are required" };
  }

  //check if user email has specific domain
  if (
    !email.endsWith("@endorphinit.com") &&
    !email.endsWith("@dovhomilja.cz")
  ) {
    return {
      error:
        "Email must end with @endorphinit.com or @dovhomilja.cz. Please contact support if you need access.",
    };
  }

  try {
    // Check if user already exists
    const existingUser = await prisma.user.findUnique({
      where: { email },
    });

    if (existingUser) {
      return { error: "User already exists with this email" };
    }

    // Hash password - CID will be auto-generated by Prisma default
    const hashedPassword = await bcrypt.hash(password, 12);

    // Create user with company in a transaction
    const result = await prisma.$transaction(async (tx) => {
      // Create user (CID will be automatically generated by Prisma)
      const user = await tx.user.create({
        data: {
          email,
          password: hashedPassword,
          name: name || null,
          emailVerified: null, // Email not verified yet
        },
        select: {
          id: true,
          email: true,
          name: true,
          createdAt: true,
        },
      });

      // Create a default company for the user
      const companyName = name ? `${name}'s Company` : `${email.split('@')[0]}'s Company`;
      const company = await tx.company.create({
        data: {
          name: companyName,
          memberships: {
            create: {
              userId: user.id,
              role: 'OWNER'
            }
          }
        }
      });

      return { user, company };
    });

    // Send verification email
    const emailResult = await sendVerificationEmail(email, name || undefined);

    if (!emailResult.success) {
      // If email fails, still return success but mention email issue
      return {
        success: true,
        user: result.user,
        message:
          "Account created but verification email failed to send. Please contact support.",
      };
    }

    return {
      success: true,
      user: result.user,
      message:
        "Account created! Please check your email to verify your account before signing in.",
    };
  } catch (error) {
    console.error("Registration error:", error);
    return { error: "Failed to create account" };
  }
}

export async function authenticateUser(formData: FormData) {
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;

  if (!email || !password) {
    return { error: "Email and password are required" };
  }

  try {
    await signIn("credentials", {
      email,
      password,
      redirectTo: "/",
    });
    return { success: true };
  } catch (error: any) {
    // Handle Next.js redirect (this is actually success)
    if (error?.digest?.includes("NEXT_REDIRECT")) {
      throw error; // Re-throw to allow the redirect to happen
    }

    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          // Check if it's an email verification error
          if (error.cause?.err?.message?.includes("verify your email")) {
            return { error: "Please verify your email before signing in" };
          }
          return { error: "Invalid email or password" };
        default:
          return { error: "Something went wrong: " + error.message };
      }
    }
    throw error;
  }
}

export async function signOutUser() {
  await signOut({
    redirectTo: "/auth/signin",
  });
}
